#!/bin/bash

# Allow incoming traffic on ports 22 (SSH), 80 (HTTP), and 443 (HTTPS SSL)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Redirect port 8080 to port 80
sudo ufw route allow 8080/tcp

# Enable UFW
sudo ufw enable

# Display UFW status
sudo ufw status
